# Generated by Django 3.2.16 on 2024-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atricles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_1', models.CharField(max_length=50, verbose_name='Присутствие в загсе')),
                ('quest_2', models.TextField(verbose_name='Предпочтение в напитках')),
                ('quest_3', models.CharField(max_length=50, verbose_name='Способ передвижения')),
                ('names', models.CharField(max_length=100, verbose_name='Имена и Фамилии')),
            ],
        ),
    ]
