# Generated by Django 3.2.16 on 2024-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имена и фамилии')),
                ('presence', models.CharField(default='Не приду', max_length=100, verbose_name='Присутствие на свадьбе')),
            ],
            options={
                'verbose_name': 'Подтверждение отсутствия',
                'verbose_name_plural': 'Подтверждение отсутствия',
            },
        ),
        migrations.AlterModelOptions(
            name='atricles',
            options={'verbose_name': 'Подтверждение присутствия', 'verbose_name_plural': 'Подтверждение присутствия'},
        ),
    ]
