# Generated by Django 3.2.16 on 2024-02-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240208_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Later',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имена и фамилии')),
                ('answer', models.CharField(default='Отвечу позже', max_length=30, verbose_name='Присутствие на свадьбе')),
            ],
            options={
                'verbose_name': 'Отвечу позже',
                'verbose_name_plural': 'Отвечу позже',
            },
        ),
    ]
