# Generated by Django 3.2.16 on 2024-03-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_later'),
    ]

    operations = [
        migrations.AlterField(
            model_name='later',
            name='answer',
            field=models.CharField(max_length=30, verbose_name='Присутствие на свадьбе'),
        ),
    ]
